# Generated by Django 5.1.1 on 2024-09-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_number',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_librarian',
        ),
    ]
