# Generated by Django 5.1.1 on 2024-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0002_rename_contact_number_user_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('librarian', 'Librarian')], default='user', max_length=10),
        ),
    ]
