# Generated by Django 5.1.1 on 2024-10-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookassignment',
            name='is_renewed',
        ),
        migrations.AddField(
            model_name='bookassignment',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('librarian', 'Librarian')], default='user', max_length=10),
        ),
    ]
