# Generated by Django 5.1.1 on 2024-10-01 05:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0005_remove_bookassignment_is_renewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=datetime.datetime(2024, 10, 1, 11, 25, 25, 116262))),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_notified', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subapp.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subapp.user')),
            ],
        ),
    ]
