# Generated by Django 5.1.1 on 2024-10-01 05:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0006_bookrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
